import { FaAws, FaGitAlt, FaNodeJs, FaPython,FaGolang } from "react-icons/fa6";
import { IoLogoJavascript } from "react-icons/io5";
import { IconType } from "react-icons/lib";
import {
	SiAppwrite,
	SiDocker,
	SiDrizzle,
	SiExpress,
	SiFramer,
	SiGithubactions,
	SiHono,
	SiMongodb,
	SiNextdotjs,
	SiPostgresql,
	SiPrisma,
	SiReact,
	SiRedux,
	SiRemix,
	SiShadcnui,
	SiTailwindcss,
	SiTypescript,
	SiVercel,
} from "react-icons/si";

export const ICON_MAP: { [key: string]: IconType } = {
	javascript: IoLogoJavascript,
	typescript: SiTypescript,
	python: FaPython,
	golang:FaGolang,
	react: SiReact,
	nextdotjs: SiNextdotjs,
	remix: SiRemix,
	redux: SiRedux,
	tailwindcss: SiTailwindcss,
	shadcnui: SiShadcnui,
	framermotion: SiFramer,
	nodedotjs: FaNodeJs,
	express: SiExpress,
	hono: SiHono,
	postgresql: SiPostgresql,
	mongodb: SiMongodb,
	prisma: SiPrisma,
	drizzle: SiDrizzle,
	appwrite: SiAppwrite,
	git: FaGitAlt,
	docker: SiDocker,
	vercel: SiVercel,
	aws: FaAws,
	githubactions: SiGithubactions,
};
