import { Project } from "@/types/project";

export const PROJECTS: Project[] = [
	{
		id: "api-gateway",
		name: "API Gateway",
		blurb: "Lightweight Go API gateway with hot‑reload configs, radix‑tree routing & adaptive balancing.",
		details: [
			"Deterministic radix‑tree matcher → low allocation routing.",
			"Round‑robin & least‑connections balancing modes.",
			"Pluggable middleware + tracing hook points.",
			"Zero‑downtime config reload (in‑flight safe).",
		],
		stack: ["Go", "Radix Tree", "Concurrency", "HTTP"],
		tags: ["Infra", "Gateway"],
		links: { code: "" },
		image: "/images/projects/api-gateway.png",
	},
	{
		id: "applic",
		name: "Applic – Job Tracker",
		blurb: "Unified job hunt workspace—track roles, statuses, interviews, notes & files in one calm surface.",
		details: [
			"Rich editor (Novel) + attachment uploads (UploadThing).",
			"Optimistic updates via Zustand cache over Postgres/Prisma.",
			"Role‑aware auth + guarded mutations.",
			"Light dashboard summarizing pipeline state.",
		],
		stack: [
			"Next.js",
			"React",
			"Tailwind",
			"ShadcnUI",
			"PostgreSQL",
			"Prisma",
			"Zustand",
			"NextAuth",
			"UploadThing",
			"Novel",
		],
		tags: ["SaaS", "Product"],
		links: {
			live: "https://applic.rahulpoonia.co",
			code: "https://something.com",
		},
		image: "https://placehold.co/200x300",
	},
	{
		id: "devmetrics",
		name: "Devmetrics Extension",
		blurb: "Local‑only VS Code extension turning Git diffs into focus & activity insights (no telemetry).",
		details: [
			"Per‑project timeline + file focus distribution.",
			"Custom TreeView + StatusBar surfacing key metrics.",
			"Embedded LokiJS store—zero network dependency.",
		],
		stack: ["VS Code API", "TypeScript", "Git", "LokiJS"],
		tags: ["Extension", "Analytics"],
		links: { code: "" },
	},
	{
		id: "form-builder",
		name: "Form Builder",
		blurb: "Visual composer that emits clean React Hook Form components + matching Zod schema.",
		details: [
			"Drag, reorder, configure fields—instant schema + JSX.",
			"Live Shiki highlighted output preview.",
			"Keeps generated layer free of proprietary wrappers.",
		],
		stack: ["React", "React Hook Form", "Zod", "Shiki"],
		tags: ["Builder"],
		links: { code: "" },
	},
	{
		id: "shad-ui",
		name: "Shad‑UI Builder",
		blurb: "Drag‑and‑drop canvas for composing Tailwind + shadcn/ui blocks with production‑ready export.",
		details: [
			"Craft.js canvas + live prop controls.",
			"Exports uncluttered, reusable JSX blocks.",
			"Focus on composability over heavy theming.",
		],
		stack: ["React", "Craft.js", "Tailwind"],
		tags: ["UI", "Drag&Drop"],
		links: { code: "" },
	},
];
