import {
  IconBrandJavascript,
  IconBrandTypescript,
  IconBrandPython,
  IconBrandGolang,
  IconBrandReact,
  IconBrandNextjs,
  //   IconBrandRemix,
  IconBrandRedux,
  IconBrandTailwind,
  IconCode, // For shadcnui (no direct match)
  IconBrandFramerMotion,
  IconBrandNodejs,
  //   IconBrandExpress,
  IconServer, // For hono (no direct match)
  //   IconBrandPostgresql,
  IconBrandMongodb,
  IconBrandPrisma,
  IconDatabase, // For drizzle (no direct match)
  IconCloud, // For appwrite (no direct match)
  IconBrandGit,
  IconBrandDocker,
  IconBrandVercel,
  IconBrandAws,
  type Icon,
  //   IconBrandGithubActions,
} from '@tabler/icons-react';

export const ICON_MAP: { [key: string]: Icon } = {
  javascript: IconBrandJavascript,
  typescript: IconBrandTypescript,
  python: IconBrandPython,
  golang: IconBrandGolang,
  react: IconBrandReact,
  nextdotjs: IconBrandNextjs,
  remix: IconCode,
  redux: IconBrandRedux,
  tailwindcss: IconBrandTailwind,
  shadcnui: IconCode,
  framermotion: IconBrandFramerMotion,
  nodedotjs: IconBrandNodejs,
  express: IconCode,
  hono: IconServer,
  postgresql: IconCode,
  mongodb: IconBrandMongodb,
  prisma: IconBrandPrisma,
  drizzle: IconDatabase,
  appwrite: IconCloud,
  git: IconBrandGit,
  docker: IconBrandDocker,
  vercel: IconBrandVercel,
  aws: IconBrandAws,
  githubactions: IconCode,
};
